#!/usr/bin/env bash
# configuring web server
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i '/location /a \    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
