#!/usr/bin/env bash
# load balancer
sudo apt update -y
sudo apt upgrade -y
sudo apt install haproxy -y
sudo sed -i "$ aENABLED=1" /etc/default/haproxy
sudo service haproxy start
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup1401
echo "
frontend loadbalancer
        bind *:80
        mode http
        default_backend webservers
backend webservers
        balance roundrobin
        server 3283-web-01 35.237.144.234:80 check
        server 3283-web-02 34.139.38.95:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
