#!/usr/bin/env bash
# Installation does not allows to listen on port 80.
# Changed default nginx conf so port 80 is allowed

sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
