#!/usr/bin/env bash                                                                           2 # Installation does not allows to listen on port 80.
# Changed default nginx conf so port 80 is allowed

sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
