#!/usr/bin/env bash
# Corrected installation does not allows to listen on port 80.
sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
