#!/usr/bin/env bash
# This script is displaying  displays numbers from 1 to 20
x=1
while [ $x -le 20 ]
do
	case $x in
		4)	echo "$x"
			echo "bad luck from China"
			;;
		9)	echo "$x"
			echo "bad luck from China"
			;;
		17)	echo "$x"
			echo "bad luck from China"
			;;
		*) echo "$x"
			;;
	esac
	x=$(( x + 1 ))
done
