#!/usr/bin/env bash
# This script is displaying  displays numbers from 1 to 20
x=1
while [ $x -le 20 ]
do
	case  $x 
		4 | 9 | 17)
		echo "bad luck from China"
		;;
	esac
	echo "Best School"
	x=$(( $x + 1 ))
done
