#!/usr/bin/env bash
# This script loops from 1 to 10 and:
# -displays bad luck for the 4th loop iteration
# -displays good luck for the 8th loop iteration
# -displays Best School for the other iterations
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo $minute
		minute=$(( minute + 1 ))
	done
	hour=$((hour + 1))
done
