#!/usr/bin/env bash
# Bash script that displays:
# -The content of the current directory
# -In a list format
# -Where only the part of the name after the first dash is displayed

directory=$(ls)
for files in $directory;
do
	    echo "$files" | cut -d'-' -f2
done
